/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutFolder: typeof import('./src/components/AboutFolder.vue')['default']
    CommentText: typeof import('./src/components/CommentText.vue')['default']
    MaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    MaterialSymbolsKeyboardArrowDown: typeof import('~icons/material-symbols/keyboard-arrow-down')['default']
    MaterialSymbolsKeyboardArrowRight: typeof import('~icons/material-symbols/keyboard-arrow-right')['default']
    MaterialSymbolsMarkdown: typeof import('~icons/material-symbols/markdown')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    PortfolioFile: typeof import('./src/components/PortfolioFile.vue')['default']
    PortfolioFolder: typeof import('./src/components/PortfolioFolder.vue')['default']
    PortfolioTab: typeof import('./src/components/PortfolioTab.vue')['default']
    ProjectItem: typeof import('./src/components/ProjectItem.vue')['default']
    ProjectsList: typeof import('./src/components/ProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolarFolderBold: typeof import('~icons/solar/folder-bold')['default']
    TechnologiesList: typeof import('./src/components/TechnologiesList.vue')['default']
    TechnologyItem: typeof import('./src/components/TechnologyItem.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
